// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhiojqppvehwdmafcnvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oaW9qcXBwdmVod2RtYWZjbnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3Mzc3NTgsImV4cCI6MjA3MDMxMzc1OH0.gyaBiO-EJlYIl8koETe1aHD3Vhw3ljtQkJ4MeY1DPS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});