// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzdaprrfactyevjxicpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6ZGFwcnJmYWN0eWV2anhpY3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDMxODYsImV4cCI6MjA3MDgxOTE4Nn0.6723ujxzrLESjhpoBMbUw-Ox1vJSGIHScZiGjzTZCgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});